name: CMakeBuild

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

jobs:
  build:
    runs-on: windows-latest

    steps:    
    - name: Clone repo
      run: git clone -b dev --recursive -j8 https://github.com/Ptyg/Document-detector.git C:\Document-detector
      
    - uses: lukka/get-cmake@latest
      
    - name: Run gen
      working-directory: C:\Document-detector
      run: cmake --preset windows-vs_gen-msvc-release